1st Article - Amari
yundom/Abigail pull request #4
Opened 2018-08-30 04:36 UTC by AliciaCChao

First review of Amari article.

2018-08-30 04:38 UTC, yundom commented on Amari/index.md
> +另外，泰國人在吃炒粿條的時候常會一口粿條一口青蔥這樣搭配吃，初次看到蠻不習慣的，入境隨俗試看看這個口感，還是比較喜歡蔥加在餐點裡的感覺啊！青蔥、豆芽、香菜及其他調味料（如辣椒＆糖）會放在店家前供消費著自行取用。
有毛病

2018-08-30 08:08 UTC, yundom requested changes

2018-08-30 08:08 UTC, yundom commented on Amari/index.md
> +你會不會好奇曼谷的上班族午餐都去吃什麼？ 今天要來介紹的是位在曼谷四面佛附近， 離 BTS Chitlom 站不遠的 **Amari Food Court**。這個在百貨公司中平價的美食廣場，是一位在曼谷工作的台灣人帶路的景點，平價實惠又多元的餐點選擇的確是上班族午餐的好選擇。
`在曼谷工作的台灣人`是偶嗎 >_<

2018-08-30 08:08 UTC, yundom commented on Amari/index.md
> +Food Court 位在Amari的四樓，中午時段前往會看到許多上班族在這用餐，我會建議避開用餐的顛峰時間(約12:00-13:00)前往，比較容易找到座位。在泰國Food Court 一般都需要先在服務台換餐卡(Cash Card)，儲值金額到卡中才能在每個店家進行消費，店家是不收現金的。餐卡(Cash Card)在用餐完後，再至服務台進行餘額的退費，如果剛好餘額用完，店家會直接把餐卡收去。
覺得可以說一下在這裡儲 100 銖就夠用了

2018-08-30 08:08 UTC, yundom commented on Amari/index.md
> +首先先來介紹鴨肉麵的部分，有別於泰式料理中的冬蔭功，因湯的口味偏重鹹，久久才能嘗試一次; 我更喜歡的是鴨肉麵這種簡單調味的湯頭，喝起來不但暖胃無負擔，且更能讓人一口接著一口把湯喝完。這次選擇的是Steam Duck with Noodles，選擇好餐點品項後，店員會讓你選擇麵的種類，我個人偏好（左二跟左三的麵條) 推薦給大家囉！
英文跟中文銜接處要加空隔 `這次選擇的是 Steam Duck with Noodles，`

2018-08-30 08:08 UTC, yundom commented on Amari/index.md
> +### Hongtay Steam Duck Noodles
我覺得可以把店名的中文翻譯也寫上來，這樣讀者在跟朋友講這家店的時候比較好講。英文名稱就是實際在找這家店的時候會用到。

2018-08-30 08:08 UTC, yundom commented on Amari/index.md
> +接著是泰國著名的經典小吃泰式炒粿條Pad Thai，將粿條加入豆乾、蝦米及豆芽菜等材料快炒，搭配泰國的Pad Thai醬汁，讓這個簡單的料理變成豐富的一道菜。Nai Meuk這間店有種Pad Thai的選擇，我們這次點的是Pad Thai with Fried Chicken的口味
加空隔唄

2018-08-30 08:08 UTC, yundom commented on Amari/index.md
> +另外，泰國人在吃炒粿條的時候常會一口粿條一口青蔥這樣搭配吃，初次看到蠻不習慣的，入境隨俗試看看這個口感，還是比較喜歡蔥加在餐點裡的感覺啊！青蔥、豆芽、香菜及其他調味料（如辣椒＆糖）會放在店家前供消費著自行取用。
可以強調一下是「生」的青蔥

2018-08-30 08:12 UTC, yundom requested changes

2018-08-30 08:12 UTC, yundom commented on Amari/index.md
> +待在曼谷兩個月的時間裡，我造訪這個Food Court大概有20次以上，其中我最常吃也是蠻推薦的兩間店家分別是 _Hongtay Steam Duck Noodles_ 的鴨肉麵 & _Nai Muek_的雞肉Pad Thai。
` _Nai Muek_的雞肉Pad Thai。` 第二個底線後面要加空隔，不然會造成語法錯誤

2018-08-30 08:27 UTC, AliciaCChao commented on Amari/index.md
> +你會不會好奇曼谷的上班族午餐都去吃什麼？ 今天要來介紹的是位在曼谷四面佛附近， 離 BTS Chitlom 站不遠的 **Amari Food Court**。這個在百貨公司中平價的美食廣場，是一位在曼谷工作的台灣人帶路的景點，平價實惠又多元的餐點選擇的確是上班族午餐的好選擇。
不然素隨 ＠＾＠

2018-08-30 08:35 UTC, AliciaCChao commented on Amari/index.md
> +接著是泰國著名的經典小吃泰式炒粿條Pad Thai，將粿條加入豆乾、蝦米及豆芽菜等材料快炒，搭配泰國的Pad Thai醬汁，讓這個簡單的料理變成豐富的一道菜。Nai Meuk這間店有種Pad Thai的選擇，我們這次點的是Pad Thai with Fried Chicken的口味
哪邊要加空格？

2018-08-31 04:05 UTC, yundom requested changes

2018-08-31 04:05 UTC, yundom commented on Amari/index.md
> +待在曼谷兩個月的時間裡，我造訪這個Food Court大概有20次以上，吃過許多Amari的店，一篇的食記實在介紹不完這邊的特色小吃，我會分兩三篇來跟大家推薦我覺得好吃的幾間店！今天要介紹的是我最常吃的兩間店家，分別是 _Hongtay Steam Duck Noodles_ 的鴨肉麵 & _Nai Muek_ 的雞肉 Pad Thai。
Food Court 前後空隔

2018-08-31 07:47 UTC, yundom approved these changes

2018-08-31 07:47 UTC, merged